spin_manifest_version = 2

[application]
name = "challenge-1"
version = "0.1.0"
authors = ["Radu Matei <radu@fermyon.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "static"

[component.static]
source = { url = "https://github.com/fermyon/spin-fileserver/releases/download/v0.2.1/spin_static_fs.wasm", digest = "sha256:5f05b15f0f7cd353d390bc5ebffec7fe25c6a6d7a05b9366c86dcb1a346e9f0f" }
files = [{ source = "static/", destination = "/" }]

[[trigger.http]]
route = "/data/..."
component = "api"

[component.api]
source = "api/target/api.wasm"
key_value_stores = ["default"]
[component.api.build]
command = "npm run build"
workdir = "api"
watch = ["src/**/*.ts"]
